package xyz.vtools;
// Generated Oct 3, 2018 11:31:00 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blocked generated by hbm2java
 */
@Entity
@Table(name = "blocked")
public class Blocked implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iid;
	private String ip;
	private Date dateCreated;
	private String decription;

	public Blocked() {
	}

	public Blocked(String ip, Date dateCreated, String decription) {
		this.ip = ip;
		this.dateCreated = dateCreated;
		this.decription = decription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iID", unique = true, nullable = false)
	public Integer getIid() {
		return this.iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	@Column(name = "IP", nullable = false, length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "decription", nullable = false)
	public String getDecription() {
		return this.decription;
	}

	public void setDecription(String decription) {
		this.decription = decription;
	}

}
