package xyz.vtools;
// Generated Oct 3, 2018 9:33:10 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logrecords generated by hbm2java
 */
@Entity
@Table(name = "logrecords")
public class Logrecords implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iid;
	private Date startDate;
	private String ip;
	private String request;
	private Integer status;
	private String useragent;

	public Logrecords() {
	}

	public Logrecords(Date startDate, String ip, String request, Integer status, String useragent) {
		this.startDate = startDate;
		this.ip = ip;
		this.request = request;
		this.status = status;
		this.useragent = useragent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iID", unique = true, nullable = false)
	public Integer getIid() {
		return this.iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "IP", length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "request", length = 100)
	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "useragent")
	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

}
